### ISSUE TITLE
"backward compatibility to the conventional NS-based delegation "

### ISSUE THREAD

**Issue by moonshiner** [moonshiner/draft-wirelela-deleg-requirements#1]
*  DELEG should allow for backward compatibility to the conventional NS-based delegation mechanism. 

I believe that should be a hard requirement. In fact, I think it should be the first hard requirement.

**Comment by moonshiner** [comment]
"DELEG may enhance existing namespace semantics, but only in ways that are backward compatible"

**Comment by vttale** [comment]
Between the wording proposed for the hard requirement in Issue #2 (or something similar) and the rest of that bullet item saying that this soft requirement was about being able to derive NS records from DELEG information, I think this is covered.

**Comment by vttale** [comment]
Addressed in 6bbb063216c0f1e7a4c827256489be95610f1ea3
