### ISSUE TITLE
We have Hard and Soft Requirements for backward compatability

### ISSUE THREAD

**Issue by moonshiner** [moonshiner/draft-wirelela-deleg-requirements#11]
Hard 

   *  DELEG must be backwards compatible with the existing ecosystem.
      Legacy zone data must function identically with both DELEG-aware
      and DELEG-unaware software.  Nameserver (NS) records will continue
      to define the delegation of authority between a parent zone and a
      child zone exactly as they have.

Soft:

   *  DELEG should allow for backward compatibility to the conventional
      NS-based delegation mechanism.  That is, a Zone Operator who wants
      to maintain a single source of truth of delegation information
      using DELEG should be able to easily have Do53 delegations derived
      from it.

**Comment by moonshiner** [comment]
I think it is fine to have both but we wordsmithed the hard requirement and we should they don't overlap./

**Comment by vttale** [comment]
They are definitely two different things, which is why they appear separately.  The hard one is basically that NS records should keep working exactly as they have.  The soft is that NS configuration should be derivable from DELEG configuration.
