### ISSUE TITLE
"current namespace semantics"

### ISSUE THREAD

**Issue by moonshiner** [moonshiner/draft-wirelela-deleg-requirements#2]
Perhaps a hard requirement of:

The nameserver (NS) record type will continue to define the delegation of authority between a parent zone and a child zone with the existing semantics.

and a soft of

DELEG may enhance existing namespace semantics, but only in ways that are backward compatible.

**Comment by vttale** [comment]
Proposed:
DELEG must be backwards compatible with the existing ecosystem. Legacy zone data must function identically with both DELEG-aware and DELEG-unaware software. Nameserver(NS)records will continue to define the delegation of authority between a parent zone and a child zone exactly as they have.

**Comment by vttale** [comment]
Addressed in 6bbb063216c0f1e7a4c827256489be95610f1ea3
