### ISSUE TITLE
Must support multiple operators

### ISSUE THREAD

**Issue by moonshiner** [moonshiner/draft-wirelela-deleg-requirements#3]
This may be a hard requirement that it must be possible to transition a domain between domain operators.

This may be a soft requirement to allow multiple simultaneous operators for a domain (eg, think what drives multi-provider DNSSEC as well as large enterprises that require vendor diversity for their authoritative zones).

**Comment by enygren** [comment]
It sounds like this a single new hard requirement should be added here, along the lines of:

* DELEG MUST enable a zone to simultaneously have multiple independent operators.

(wordsmithing is most welcome)

**Comment by vttale** [comment]
I also wanted to say something like "DELEG must not make it harder to switch operators" but I don't think we can actually say something like that.  To the extent that a zone is using deleg with an operator that supports it, it would have an impact on their options for other operators.
