### ISSUE TITLE
"enable a DNS operator to manage DNS service more completely on behalf of registrants"

### ISSUE THREAD

**Issue by vttale** [moonshiner/draft-wirelela-deleg-requirements#4]
Discussion in the chat during the deleg meeting suggested that maybe this was a little too meta about just what was meant, but it also wasn't clear that the actual content of the document was being replied to.  But maybe add another phrase at also being able to support operators being able to update the names of nameserver targets.

**Comment by vttale** [comment]
Proposed:
   DELEG should enable a DNS operator to manage DNS service more
   completely on behalf of domain administrators. For example, DELEG
   could address long-standing issues of DNSSEC record maintenance
   that now often depend on registrant / registrar interaction.
   Similarly, DELEG could allow new transports to be deployed by an
   operator or nameserver names to be changed, without necessitating
   that delegation information be modified by the domain administrator.

**Comment by enygren** [comment]
Makes sense to me.

**Comment by moonshiner** [comment]
Is this hard or soft requirement?

**Comment by enygren** [comment]
I think a hard requirement as otherwise it is a substantial regression
relative to today.

**Comment by moonshiner** [comment]
agreed it should be a hard requirement.  just wanting it called out.

**Comment by vttale** [comment]
This comes from soft requirements because it is attempting to solve one of the existing problems.  It isn't a regression to not address it; it is the status quo to not address it.  (This is separate from the multiple operators issue, which is a hard requirement and would be a regression.)

**Comment by vttale** [comment]
Addressed in 71ec5c000efcec8cae28c70d003b24b0dbc385d5
