### ISSUE TITLE
will NS be forever required or aim to be eventually dead

### ISSUE THREAD

**Issue by vttale** [moonshiner/draft-wirelela-deleg-requirements#6]
Maybe we need a section on "not a requirement" that this be addressed; that current work cannot really address whether future NS use is either mandatory not intended to be obsoleted

**Comment by moonshiner** [comment]
can we define deleg requirements mentioning NS or DS records ? 
(or orthogonal)

**Comment by moonshiner** [comment]
paulh "the addition of DELEG records does not change that".
